from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Literal


QuickAdbParam = Literal["package", "bugreport_path"]


@dataclass(frozen=True)
class QuickAdbCommand:
    command_id: str
    title: str
    description: str
    layer: str
    group: str
    args: tuple[str, ...]
    params: tuple[QuickAdbParam, ...] = ()
    timeout_seconds: int = 20
    risk: str = "safe"

    def render_args(self, *, package_name: str = "", artifact_dir: Path | None = None) -> tuple[str, ...]:
        values = {
            "package": package_name,
            "bugreport_path": str((artifact_dir or Path("runtime/quick_adb")) / "bugreport.zip"),
        }
        rendered: list[str] = []
        for arg in self.args:
            value = arg
            for key, replacement in values.items():
                value = value.replace("{" + key + "}", replacement)
            rendered.append(value)
        return tuple(rendered)


QUICK_ADB_LAYERS: tuple[dict[str, str], ...] = (
    {"key": "app", "label": "App 层", "bridge": "Java / Kotlin API"},
    {"key": "framework", "label": "Framework 层", "bridge": "Binder IPC"},
    {"key": "system_server", "label": "System Server / 系统服务", "bridge": "Binder / Socket / Native 调用"},
    {"key": "native_service", "label": "Native Service / 系统 Native 组件", "bridge": "HIDL / AIDL HAL / JNI / ioctl / sysfs"},
    {"key": "hal", "label": "HAL 层", "bridge": "驱动接口"},
    {"key": "kernel", "label": "Kernel / Driver 层", "bridge": "内核日志 / procfs / sysfs / pstore"},
    {"key": "hardware", "label": "硬件", "bridge": "由上层状态和内核证据间接定位"},
)


QUICK_ADB_COMMANDS: tuple[QuickAdbCommand, ...] = (
    QuickAdbCommand(
        "app_processes",
        "查看全部进程",
        "确认 App 进程、系统进程是否存在，以及进程名/PID 基线。",
        "app",
        "进程与前台状态",
        ("shell", "ps", "-A"),
    ),
    QuickAdbCommand(
        "app_top_once",
        "Top 快照",
        "抓取一次 CPU/线程占用快照。",
        "app",
        "进程与前台状态",
        ("shell", "top", "-n", "1"),
        timeout_seconds=12,
    ),
    QuickAdbCommand(
        "app_activity_top",
        "当前前台 Activity",
        "查看当前 resumed/top activity 和 task 栈摘要。",
        "app",
        "进程与前台状态",
        ("shell", "dumpsys", "activity", "top"),
    ),
    QuickAdbCommand(
        "app_meminfo_package",
        "App 内存详情",
        "按包名查看 PSS、Dalvik/native heap、对象和图形内存。",
        "app",
        "包与权限",
        ("shell", "dumpsys", "meminfo", "{package}"),
        params=("package",),
        timeout_seconds=25,
    ),
    QuickAdbCommand(
        "app_package",
        "Package 信息",
        "按包名查看安装路径、版本、组件、签名和授权状态。",
        "app",
        "包与权限",
        ("shell", "dumpsys", "package", "{package}"),
        params=("package",),
    ),
    QuickAdbCommand(
        "app_ops",
        "AppOps 状态",
        "按包名查看敏感权限/后台行为的 AppOps 开关。",
        "app",
        "包与权限",
        ("shell", "dumpsys", "appops", "{package}"),
        params=("package",),
    ),
    QuickAdbCommand(
        "app_gfxinfo_framestats",
        "App 帧统计",
        "按包名查看 gfxinfo framestats，用于对齐卡顿、掉帧和响应延迟现场。",
        "app",
        "帧率与响应",
        ("shell", "dumpsys", "gfxinfo", "{package}", "framestats"),
        params=("package",),
        timeout_seconds=25,
    ),
    QuickAdbCommand(
        "framework_activity",
        "ActivityManager 全量",
        "查看 Activity、Task、Service、Provider 和进程调度状态。",
        "framework",
        "核心 Framework 服务",
        ("shell", "dumpsys", "activity"),
        timeout_seconds=25,
    ),
    QuickAdbCommand(
        "framework_window",
        "WindowManager",
        "查看焦点窗口、窗口层级、输入目标和可见性。",
        "framework",
        "核心 Framework 服务",
        ("shell", "dumpsys", "window"),
    ),
    QuickAdbCommand(
        "framework_input",
        "InputManager",
        "查看输入设备、分发状态、焦点和事件通道。",
        "framework",
        "核心 Framework 服务",
        ("shell", "dumpsys", "input"),
    ),
    QuickAdbCommand(
        "framework_permissions",
        "Permission 状态",
        "查看系统权限定义、授权和运行时权限状态。",
        "framework",
        "包与权限",
        ("shell", "dumpsys", "permission"),
    ),
    QuickAdbCommand(
        "framework_activity_anr",
        "ANR 状态",
        "查看 ActivityManager 记录的 ANR 摘要，辅助定位 traces 和阻塞窗口。",
        "framework",
        "日志与证据",
        ("shell", "dumpsys", "activity", "anr"),
    ),
    QuickAdbCommand(
        "framework_anr_files",
        "ANR 文件列表",
        "列出 /data/anr 下最近 traces 文件；部分 user build 可能没有权限。",
        "framework",
        "日志与证据",
        ("shell", "ls -lt /data/anr 2>/dev/null | head -n 30"),
        risk="may_require_privilege",
    ),
    QuickAdbCommand(
        "framework_dropbox_recent",
        "DropBox 近期记录",
        "查看系统异常索引，快速确认 crash、anr、watchdog、lowmem 等记录是否存在。",
        "framework",
        "日志与证据",
        ("shell", "dumpsys dropbox --print | tail -n 240"),
        timeout_seconds=25,
    ),
    QuickAdbCommand(
        "framework_events_tail",
        "Event Log 尾部",
        "查看 events buffer 最近记录，用于定位 am_anr、am_proc_died、boot 等系统事件时间点。",
        "framework",
        "日志与证据",
        ("logcat", "-d", "-b", "events", "-v", "threadtime", "-t", "300"),
        timeout_seconds=20,
    ),
    QuickAdbCommand(
        "system_server_process",
        "system_server 进程",
        "确认 system_server 是否存在及 PID，辅助判断系统服务重启。",
        "system_server",
        "系统服务进程",
        ("shell", "ps -A | grep system_server"),
    ),
    QuickAdbCommand(
        "system_power",
        "PowerManager",
        "查看 wakelock、休眠、亮屏和电源状态。",
        "system_server",
        "电源与显示",
        ("shell", "dumpsys", "power"),
    ),
    QuickAdbCommand(
        "system_display",
        "DisplayManager",
        "查看显示设备、刷新率、亮度和 display state。",
        "system_server",
        "电源与显示",
        ("shell", "dumpsys", "display"),
    ),
    QuickAdbCommand(
        "system_cpuinfo",
        "CPU 使用摘要",
        "查看系统按进程聚合的 CPU 使用情况，辅助 CPU 高负载、卡顿和非 root Binder 替代诊断。",
        "system_server",
        "资源与调度",
        ("shell", "dumpsys", "cpuinfo"),
        timeout_seconds=25,
    ),
    QuickAdbCommand(
        "system_binder_calls_stats_enable",
        "Binder calls stats 开启",
        "生产机无法读取 binder state 时，开启 Binder IPC 调用采样；建议 reset 后复现问题再 dump。",
        "system_server",
        "非 root Binder 替代诊断",
        ("shell", "dumpsys", "binder_calls_stats", "--enable"),
        timeout_seconds=15,
    ),
    QuickAdbCommand(
        "system_binder_calls_stats_reset",
        "Binder calls stats 重置",
        "清空旧的 Binder IPC 调用统计，便于只观察下一次复现窗口的数据。",
        "system_server",
        "非 root Binder 替代诊断",
        ("shell", "dumpsys", "binder_calls_stats", "--reset"),
        timeout_seconds=15,
    ),
    QuickAdbCommand(
        "system_binder_calls_stats",
        "Binder calls stats",
        "查看 Binder IPC 调用次数、CPU 时间、异常和调用分布，适合 user/release 设备替代 binder state。",
        "system_server",
        "非 root Binder 替代诊断",
        ("shell", "dumpsys", "binder_calls_stats"),
        timeout_seconds=25,
    ),
    QuickAdbCommand(
        "system_looper_stats",
        "Looper stats",
        "查看 system_server 等 Looper/Handler 消息耗时，用于定位主线程或系统线程消息堆积。",
        "system_server",
        "非 root Binder 替代诊断",
        ("shell", "dumpsys", "looper_stats"),
        timeout_seconds=25,
    ),
    QuickAdbCommand(
        "system_procstats_1h",
        "ProcStats 1h",
        "查看最近 1 小时进程驻留、状态和内存趋势，辅助判断后台进程压力和系统稳定性。",
        "system_server",
        "非 root Binder 替代诊断",
        ("shell", "dumpsys", "procstats", "--hours", "1"),
        timeout_seconds=30,
    ),
    QuickAdbCommand(
        "system_battery",
        "Battery 当前状态",
        "查看电量、充电、温度、电压等当前状态，辅助功耗和低电量场景排查。",
        "system_server",
        "功耗与温升",
        ("shell", "dumpsys", "battery"),
    ),
    QuickAdbCommand(
        "system_batterystats_charged",
        "BatteryStats charged",
        "查看自上次充满以来的 wakelock、alarm、job、网络和传感器使用摘要。",
        "system_server",
        "功耗与温升",
        ("shell", "dumpsys", "batterystats", "--charged"),
        timeout_seconds=35,
    ),
    QuickAdbCommand(
        "system_thermalservice",
        "ThermalService",
        "查看系统热状态、thermal throttling 和温控服务摘要。",
        "system_server",
        "功耗与温升",
        ("shell", "dumpsys", "thermalservice"),
    ),
    QuickAdbCommand(
        "system_deviceidle",
        "DeviceIdle",
        "查看 Doze/device idle 状态，辅助后台行为和功耗异常定位。",
        "system_server",
        "后台调度",
        ("shell", "dumpsys", "deviceidle"),
    ),
    QuickAdbCommand(
        "system_alarm",
        "AlarmManager",
        "查看 alarm 触发与唤醒统计，辅助后台频繁唤醒定位。",
        "system_server",
        "后台调度",
        ("shell", "dumpsys", "alarm"),
        timeout_seconds=25,
    ),
    QuickAdbCommand(
        "system_jobscheduler",
        "JobScheduler",
        "查看 job 调度、失败重试和后台任务状态。",
        "system_server",
        "后台调度",
        ("shell", "dumpsys", "jobscheduler"),
        timeout_seconds=25,
    ),
    QuickAdbCommand(
        "native_processes",
        "Native 服务进程",
        "快速查看 surfaceflinger、audioserver、cameraserver、media、netd、vold 等 Native 组件。",
        "native_service",
        "Native 服务",
        ("shell", 'ps -A | grep -E "surfaceflinger|audioserver|cameraserver|media|netd|vold"'),
    ),
    QuickAdbCommand(
        "native_surfaceflinger",
        "SurfaceFlinger",
        "查看合成、图层、显示管线和帧相关状态。",
        "native_service",
        "图形与媒体",
        ("shell", "dumpsys", "SurfaceFlinger"),
        timeout_seconds=25,
    ),
    QuickAdbCommand(
        "native_surfaceflinger_latency",
        "SurfaceFlinger latency",
        "查看 SurfaceFlinger 显示帧时间戳，辅助卡顿和黑屏时间线对齐。",
        "native_service",
        "图形与媒体",
        ("shell", "dumpsys", "SurfaceFlinger", "--latency"),
        timeout_seconds=20,
    ),
    QuickAdbCommand(
        "native_camera",
        "Camera Service",
        "查看 camera provider、设备枚举、客户端和错误状态。",
        "native_service",
        "图形与媒体",
        ("shell", "dumpsys", "media.camera"),
    ),
    QuickAdbCommand(
        "native_audio",
        "Audio Service",
        "查看音频路由、焦点、策略和 native audio 状态。",
        "native_service",
        "图形与媒体",
        ("shell", "dumpsys", "audio"),
    ),
    QuickAdbCommand(
        "native_connectivity",
        "Connectivity",
        "查看网络、NetworkAgent、默认网络和连接策略。",
        "native_service",
        "网络与存储",
        ("shell", "dumpsys", "connectivity"),
    ),
    QuickAdbCommand(
        "native_tombstone_files",
        "Tombstone 文件列表",
        "列出 /data/tombstones 最近文件，辅助 Native Crash 证据定位；部分 user build 可能没有权限。",
        "native_service",
        "Native 证据",
        ("shell", "ls -lt /data/tombstones 2>/dev/null | head -n 30"),
        risk="may_require_privilege",
    ),
    QuickAdbCommand(
        "hal_binder_state",
        "Binder state",
        "查看 binder 调用、线程和等待状态；user/release 非 root 设备通常不可读，请改用 Binder calls stats、Looper stats、CPU 和 ProcStats。",
        "hal",
        "Binder / HAL 调用",
        (
            "shell",
            "for p in /sys/kernel/debug/binder/state /dev/binderfs/binder_logs/state; do "
            'if [ -r "$p" ]; then echo "== $p =="; head -n 240 "$p"; exit $?; fi; '
            "done; "
            'echo "binder state 不可读：需要 root/userdebug/eng，或设备未挂载 binder debugfs/binderfs。"; '
            "ls -ld /sys/kernel/debug/binder /dev/binderfs/binder_logs 2>&1; exit 0",
        ),
        timeout_seconds=15,
        risk="may_require_privilege",
    ),
    QuickAdbCommand(
        "kernel_meminfo",
        "Kernel 内存",
        "读取 /proc/meminfo，判断系统级内存压力。",
        "kernel",
        "procfs",
        ("shell", "cat", "/proc/meminfo"),
    ),
    QuickAdbCommand(
        "kernel_uptime",
        "Kernel Uptime",
        "读取 /proc/uptime，判断是否发生过重启或异常恢复。",
        "kernel",
        "procfs",
        ("shell", "cat", "/proc/uptime"),
    ),
    QuickAdbCommand(
        "kernel_df",
        "文件系统空间",
        "查看分区空间使用，辅助存储满、写入失败和 I/O 阻塞定位。",
        "kernel",
        "存储与 I/O",
        ("shell", "df", "-h"),
    ),
    QuickAdbCommand(
        "kernel_df_inode",
        "inode 使用",
        "查看 inode 使用情况，辅助大量小文件导致的存储异常定位。",
        "kernel",
        "存储与 I/O",
        ("shell", "df", "-i"),
    ),
    QuickAdbCommand(
        "kernel_io_pressure",
        "I/O Pressure",
        "读取 /proc/pressure/io，判断是否存在系统级 I/O 压力；部分内核可能不支持。",
        "kernel",
        "存储与 I/O",
        ("shell", "cat /proc/pressure/io 2>/dev/null"),
        risk="may_require_privilege",
    ),
    QuickAdbCommand(
        "kernel_diskstats",
        "proc diskstats",
        "读取 /proc/diskstats，辅助观察块设备 I/O 变化。",
        "kernel",
        "存储与 I/O",
        ("shell", "cat", "/proc/diskstats"),
    ),
    QuickAdbCommand(
        "kernel_dumpsys_diskstats",
        "DiskStats 服务",
        "查看 Android diskstats 服务输出，辅助存储性能和空间问题定位。",
        "kernel",
        "存储与 I/O",
        ("shell", "dumpsys", "diskstats"),
    ),
    QuickAdbCommand(
        "kernel_storaged",
        "Storaged 服务",
        "查看 storaged 统计，辅助 I/O、磨损和存储健康方向排查。",
        "kernel",
        "存储与 I/O",
        ("shell", "dumpsys", "storaged"),
    ),
    QuickAdbCommand(
        "kernel_thermal_zones",
        "Thermal zone 快照",
        "读取 thermal zone 温度快照；不同平台传感器命名差异较大。",
        "kernel",
        "温度与频率",
        ("shell", "for z in /sys/class/thermal/thermal_zone*/temp; do echo $z=$(cat $z 2>/dev/null); done"),
        timeout_seconds=15,
        risk="may_require_privilege",
    ),
    QuickAdbCommand(
        "kernel_cpu_freq",
        "CPU 当前频率",
        "读取各 CPU 当前频率，辅助降频、温升和性能抖动排查。",
        "kernel",
        "温度与频率",
        ("shell", "for c in /sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq; do echo $c=$(cat $c 2>/dev/null); done"),
        timeout_seconds=15,
        risk="may_require_privilege",
    ),
    QuickAdbCommand(
        "kernel_dmesg",
        "dmesg",
        "查看内核日志；部分 user build 可能没有权限。",
        "kernel",
        "内核日志",
        ("shell", "dmesg"),
        timeout_seconds=15,
        risk="may_require_privilege",
    ),
    QuickAdbCommand(
        "kernel_pstore_list",
        "pstore 列表",
        "查看是否存在 ramoops/console-ramoops 崩溃保留日志。",
        "kernel",
        "pstore",
        ("shell", "ls", "/sys/fs/pstore"),
        risk="may_require_privilege",
    ),
    QuickAdbCommand(
        "kernel_pstore_console",
        "console-ramoops",
        "读取 pstore console-ramoops；无文件或无权限时会返回错误。",
        "kernel",
        "pstore",
        ("shell", "cat /sys/fs/pstore/console-ramoops*"),
        timeout_seconds=15,
        risk="may_require_privilege",
    ),
    QuickAdbCommand(
        "bootreason_ro",
        "ro.boot.bootreason",
        "查看 bootloader/kernel 传入的启动原因。",
        "hardware",
        "启动原因",
        ("shell", "getprop", "ro.boot.bootreason"),
    ),
    QuickAdbCommand(
        "build_fingerprint",
        "Build Fingerprint",
        "查看系统 build fingerprint，便于准入、复盘和跨版本对比。",
        "hardware",
        "版本与环境",
        ("shell", "getprop", "ro.build.fingerprint"),
    ),
    QuickAdbCommand(
        "vendor_fingerprint",
        "Vendor Fingerprint",
        "查看 vendor build fingerprint，辅助判断系统/vendor 版本是否匹配。",
        "hardware",
        "版本与环境",
        ("shell", "getprop", "ro.vendor.build.fingerprint"),
    ),
    QuickAdbCommand(
        "build_incremental",
        "Build Incremental",
        "查看增量版本号，便于日报、准入和问题样本归档。",
        "hardware",
        "版本与环境",
        ("shell", "getprop", "ro.build.version.incremental"),
    ),
    QuickAdbCommand(
        "verified_boot_state",
        "Verified Boot",
        "查看 verified boot 状态，辅助确认设备环境和安全状态是否符合测试基线。",
        "hardware",
        "版本与环境",
        ("shell", "getprop", "ro.boot.verifiedbootstate"),
    ),
    QuickAdbCommand(
        "bootreason_sys",
        "sys.boot.reason",
        "查看 Android 记录的系统启动原因。",
        "hardware",
        "启动原因",
        ("shell", "getprop", "sys.boot.reason"),
    ),
    QuickAdbCommand(
        "logs_all_threadtime",
        "Logcat 快照",
        "抓取所有 buffer 的 threadtime 日志快照；使用 -d 一次性导出。",
        "framework",
        "日志与证据",
        ("logcat", "-d", "-b", "all", "-v", "threadtime"),
        timeout_seconds=30,
    ),
    QuickAdbCommand(
        "bugreport_zip",
        "Bugreport ZIP",
        "生成完整 bugreport zip，文件落到 runtime/quick_adb。",
        "framework",
        "日志与证据",
        ("bugreport", "{bugreport_path}"),
        params=("bugreport_path",),
        timeout_seconds=180,
        risk="slow",
    ),
)


def quick_adb_command_by_id(command_id: str) -> QuickAdbCommand | None:
    for command in QUICK_ADB_COMMANDS:
        if command.command_id == command_id:
            return command
    return None
